name: netflix
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  carousel_slider: ^4.2.1
  http: ^1.2.2
  animations: ^2.0.11
  card_swiper: ^3.0.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  intl_phone_field: ^3.2.0
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.1.2
  connectivity: ^3.0.6
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8

  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

